INSERT INTO Employee (FirstName, LastName, Email) VALUES ('Nicholas', 'Smith', 'taylorkara@example.org');
INSERT INTO Employee (FirstName, LastName, Email) VALUES ('Lisa', 'Nelson', 'anne14@example.net');
INSERT INTO Employee (FirstName, LastName, Email) VALUES ('Daniel', 'Martinez', 'duane75@example.net');
INSERT INTO Employee (FirstName, LastName, Email) VALUES ('Kenneth', 'Sloan', 'frederick37@example.org');
INSERT INTO Employee (FirstName, LastName, Email) VALUES ('Shelby', 'Hinton', 'blairemily@example.com');
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (2, '2022-10-21', 'Let life in.', 471.68);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (1, '2022-12-16', 'Change section hard produce card.', 179.69);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (2, '2022-05-17', 'Late class condition bed.', 148.67);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (2, '2022-08-18', 'Yeah product student democratic main than pick.', 113.02);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (2, '2023-01-13', 'Effort mission wish arrive and current beat.', 228.06);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (3, '2022-07-12', 'Room majority drop still list.', 220.78);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (2, '2022-11-23', 'Girl able employee west lawyer other assume.', 470.46);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (3, '2022-03-21', 'Beautiful pretty simply soon prevent.', 450.55);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (5, '2023-01-16', 'Very born to likely certain fire condition.', 345.8);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (3, '2022-12-09', 'Student media cultural sea behavior really direction.', 493.0);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (4, '2022-09-23', 'Movie all different alone send effort.', 426.48);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (2, '2022-12-06', 'Respond economic enough finish never provide.', 204.05);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (4, '2022-07-10', 'Government court fact technology.', 492.2);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (3, '2022-02-13', 'Measure technology game increase.', 198.21);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (5, '2022-10-20', 'Prepare boy but language kid compare.', 31.74);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (4, '2022-06-27', 'Out national home it use stay down.', 207.09);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (3, '2022-08-18', 'Night education after manager moment accept.', 305.05);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (2, '2022-07-20', 'May cup year response majority.', 428.34);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (3, '2022-09-07', 'Yeah since out moment stand.', 491.29);
INSERT INTO Expense (EmployeeID, Date, Description, Amount) VALUES (2, '2022-10-30', 'Music next film outside.', 162.96);
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (1, 'Travel');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (2, 'Other');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (3, 'Office Supplies');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (4, 'Meals');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (5, 'Travel');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (6, 'Travel');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (7, 'Meals');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (8, 'Other');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (9, 'Meals');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (10, 'Travel');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (11, 'Office Supplies');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (12, 'Office Supplies');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (13, 'Other');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (14, 'Meals');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (15, 'Travel');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (16, 'Meals');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (17, 'Meals');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (18, 'Meals');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (19, 'Meals');
INSERT INTO ExpenseCategory (ExpenseID, Category) VALUES (20, 'Meals');
INSERT INTO Receipt (ExpenseID, Image) VALUES (1, 'https://picsum.photos/431/246');
INSERT INTO Receipt (ExpenseID, Image) VALUES (2, 'https://placeimg.com/597/77/any');
INSERT INTO Receipt (ExpenseID, Image) VALUES (3, 'https://dummyimage.com/720x364');
INSERT INTO Receipt (ExpenseID, Image) VALUES (4, 'https://placekitten.com/164/1020');
INSERT INTO Receipt (ExpenseID, Image) VALUES (5, 'https://placeimg.com/894/376/any');
INSERT INTO Receipt (ExpenseID, Image) VALUES (6, 'https://dummyimage.com/758x1000');
INSERT INTO Receipt (ExpenseID, Image) VALUES (7, 'https://dummyimage.com/367x73');
INSERT INTO Receipt (ExpenseID, Image) VALUES (8, 'https://placekitten.com/841/722');
INSERT INTO Receipt (ExpenseID, Image) VALUES (9, 'https://placekitten.com/731/993');
INSERT INTO Receipt (ExpenseID, Image) VALUES (10, 'https://dummyimage.com/85x268');
INSERT INTO Receipt (ExpenseID, Image) VALUES (11, 'https://dummyimage.com/224x496');
INSERT INTO Receipt (ExpenseID, Image) VALUES (12, 'https://placekitten.com/756/305');
INSERT INTO Receipt (ExpenseID, Image) VALUES (13, 'https://placeimg.com/520/912/any');
INSERT INTO Receipt (ExpenseID, Image) VALUES (14, 'https://placekitten.com/861/154');
INSERT INTO Receipt (ExpenseID, Image) VALUES (15, 'https://placeimg.com/856/446/any');
INSERT INTO Receipt (ExpenseID, Image) VALUES (16, 'https://picsum.photos/679/644');
INSERT INTO Receipt (ExpenseID, Image) VALUES (17, 'https://placeimg.com/417/137/any');
INSERT INTO Receipt (ExpenseID, Image) VALUES (18, 'https://picsum.photos/183/398');
INSERT INTO Receipt (ExpenseID, Image) VALUES (19, 'https://picsum.photos/802/635');
INSERT INTO Receipt (ExpenseID, Image) VALUES (20, 'https://dummyimage.com/357x594');
